SRC=../src
CXX=g++
CXXFLAGS+=-I../include -std=gnu++11 -DSEQAN_HAS_ZLIB=1
LDFLAGS+=-lz

# Only define defaults and all if we're not running tests.
ifeq ($(TESTS),)
  default: main
  all: main

	clean:
		rm -f *.o main
else
  default:
  all:
endif

main: main.o parse_gaps.o
	$(CXX) $(LDFLAGS) -o $@ $<

%.o: $(SRC)/%.cpp
	$(CXX) $(CXXFLAGS) -c -o $@ $<

.PHONY: default all clean
